# Generated by Django 2.2.3 on 2026-03-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('soundID', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('soundFile', models.URLField()),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(default=0, max_length=15)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('savedSound', models.ManyToManyField(related_name='saved_sounds', through='app.SavedSound', to='app.User')),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_sounds', to='app.User')),
            ],
        ),
        migrations.AddField(
            model_name='savedsound',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sound'),
        ),
        migrations.AddField(
            model_name='savedsound',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='savedsound',
            unique_together={('user', 'sound')},
        ),
    ]
