# Generated by Django 2.2.3 on 2026-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='soundFile',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='soundID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
